-- Structural UI contract for Shir's LazyTrix

local root = arg and arg[1] or "."
local path = root .. "/ShirsLazyTrix_UI.lua"
local file = io.open(path, "rb")
if not file then
  error("missing ShirsLazyTrix_UI.lua", 2)
end
local source = file:read("*a")
file:close()

local function assertContains(text, message)
  if not string.find(source, text, 1, true) then
    error(message .. ": missing " .. text, 2)
  end
end

local function assertAbsent(text, message)
  if string.find(string.lower(source), string.lower(text), 1, true) then
    error(message .. ": found " .. text, 2)
  end
end

local function count(text)
  local total = 0
  local start = 1
  while true do
    local found = string.find(source, text, start, true)
    if not found then return total end
    total = total + 1
    start = found + string.len(text)
  end
end

assertContains('frame:SetWidth(620)', "two-column settings width")
assertContains('frame:SetHeight(600)', "compact settings height")
assertContains('UI-Tooltip-Background', "addon-family dark panel background")
assertContains('UI-Tooltip-Border', "addon-family thin panel border")
assertContains('frame:SetBackdropColor(0.025, 0.035, 0.055, 0.98)', "dark navy panel color")
assertContains('frame:SetBackdropBorderColor(0.3, 0.6, 0.9, 1)', "blue panel border")
assertContains('title:SetTextColor(0.45, 0.82, 1)', "blue addon title")
assertContains('"QUESTING"', "questing section heading")
assertContains('"WORLD"', "world section heading")
assertContains('"TRAINERS"', "trainer section heading")
assertContains('verticalDivider:SetHeight(510)', "two-column divider height")
assertContains('section:SetTextColor(1, 0.82, 0)', "gold section heading")
assertContains('button:SetWidth(32)', "standard minimap button width")
assertContains('button:SetHeight(32)', "standard minimap button height")
assertContains('icon:SetWidth(20)', "filled minimap icon width")
assertContains('icon:SetHeight(20)', "filled minimap icon height")
assertContains('button:CreateTexture(nil, "ARTWORK")', "icon artwork layer")
assertContains('Interface\\\\AddOns\\\\ShirsLazyTrix\\\\LazyTrixIcon', "custom LazyTrix icon")
assertContains('MiniMap-TrackingBorder', "minimap tracking border")
assertContains('border:SetWidth(52)', "standard border width")
assertContains('button:RegisterForDrag("LeftButton")', "movable minimap registration")
assertContains('ShirsLazyTrixDB.minimapAngle', "saved minimap angle")
assertContains('math.atan2', "cursor angle calculation")
assertContains('"Drag: Move this button"', "minimap drag tooltip")
assertContains('"Turn in completed quests", "turnIn"', "turn-in checkbox")
assertContains('"Pick up quests", "pickUp"', "pickup checkbox")
assertContains('"Only automate while Shift is held", "automationOnShift"', "Shift-required automation checkbox")
assertContains("Shift can trigger both pickup and turn-in.", "Shift behavior note")
assertContains('"Accept open-world resurrection requests", "autoAcceptOpenWorldRes"', "open-world resurrection checkbox")
assertContains('"Remove immolation on stealth or invisibility", "autoRemoveImmolationOnStealth"', "stealth immolation cleanup checkbox")
assertContains('"Invite from whispers", "inviteFromWhispers"', "whisper invite checkbox")
assertContains('"Invite from guild chat", "inviteFromGuild"', "guild invite checkbox")
assertContains('"ShirsLazyTrixInvitePhrases"', "invite phrase input")
assertContains('Comma-separated phrases.', "invite phrase help")
assertContains('invitePhrases:SetScript("OnTextChanged"', "invite phrase live-save handler")
assertContains('"Expand trainer windows", "expandTrainers"', "expanded trainer checkbox")
assertContains('"Enable Train All", "trainAll"', "Train All checkbox")
assertContains('"Automatically open trainer services", "autoOpenTrainers"', "automatic trainer gossip checkbox")
assertContains('"Show movable cooldown panel", "showCooldownPanel"', "profession cooldown panel checkbox")
assertContains('"Show raid reset panel", "showRaidInfoPanel"', "raid reset panel checkbox")
assertContains('"Hide in combat and instances", "hideCooldownPanelInCombat"', "cooldown combat-and-instance-hide checkbox")
assertContains('"OTHER-CHARACTER READY REMINDERS"', "other-character reminder heading")
assertContains('"Mooncloth", "notifyOtherMooncloth"', "Mooncloth reminder checkbox")
assertContains('"Arcanite", "notifyOtherArcanite"', "Arcanite reminder checkbox")
assertContains('"Salt", "notifyOtherSalt"', "Salt Shaker reminder checkbox")
assertContains('"TOOLTIPS"', "tooltip section heading")
assertContains('"Show item IDs in tooltips", "showItemIDs"', "item-ID tooltip checkbox")
assertContains('"Collect addon minimap buttons"', "minimap collector checkbox")
assertContains('"Expand Blizzard loot rows", "expandLootRows"', "loot expansion checkbox")
assertContains('"ShirsLazyTrixLootRowsSlider"', "stock loot row slider")
assertContains('"ShirsLazyTrixMinimapButtonSizeSlider"', "collected minimap button size slider")
assertContains('"PROFESSION COOLDOWNS"', "profession cooldown section heading")
assertContains('local SETTINGS_CONTENT_RISE = 4', "settings content upward nudge")
assertContains('local RAID_SETTINGS_CONTENT_RISE = 30', "raid settings gap tightening")
assertContains('raidSettingsY(-292)', "raid settings use scoped upward nudge")
assertContains('local raidSection = createText(frame, "RAID RESET INFO", 11)', "separate raid reset settings section")
assertContains('"Show raid reset panel", "showRaidInfoPanel", raidSettingsY(-364), 326, 260', "raid reset checkbox placement")
assertContains('"Show CCP raid schedules", "showRaidInfoSchedule", raidSettingsY(-392), 326, 260', "CCP schedule checkbox placement")
assertContains('tooltipSection:SetPoint("TOPLEFT", frame, "TOPLEFT", 326, raidSettingsY(-434))', "tooltip heading clears CCP schedule checkbox")
assertContains('"Show item IDs in tooltips", "showItemIDs", raidSettingsY(-449), 326, 260', "item-ID checkbox follows tooltip heading")
assertContains('interfaceSection:SetPoint("TOPLEFT", frame, "TOPLEFT", 326, raidSettingsY(-492))', "loot section follows tooltip controls")
assertContains('raidSettingsY(-507)', "minimap collector placement after loot heading")
assertContains('raidSettingsY(-520)', "loot expansion placement after minimap collector")
assertContains('raidSettingsY(-568)', "loot sliders clear their checkboxes")
assertContains('reminderLabel:SetPoint("TOPLEFT", frame, "TOPLEFT", 326, raidSettingsY(-292))', "ready reminders placement")
assertContains('local RAID_INFO_PANEL_WIDTH = 250', "matching raid panel width")
assertContains('local RAID_INFO_ROW_WIDTH = 222', "matching raid row width")
assertContains('CreateFrame("Frame", "ShirsLazyTrixCooldownPanel", UIParent)', "movable cooldown panel")
assertContains('CreateFrame("Button", "ShirsLazyTrixCooldownMooncloth"', "clickable Mooncloth row")
assertContains('CreateFrame("Frame", "ShirsLazyTrixRaidInfoPanel", UIParent)', "movable raid info panel")
assertContains('panel:SetHeight(RAID_INFO_PANEL_EMPTY_HEIGHT)', "compact empty raid panel height")
assertContains('panelHeight = RAID_INFO_PANEL_MIN_HEIGHT + ((visibleRows - 1) * RAID_INFO_ROW_SPACING)', "row-count raid panel height")
assertContains('ShirsLazyTrixRaidInfoPanel:SetHeight(panelHeight)', "dynamic raid panel resize")
assertContains('CreateFrame("Button", "ShirsLazyTrixRaidInfoRow" .. index', "raid reset rows")
assertContains('CreateFrame("Button", "ShirsLazyTrixRaidInfoLock"', "raid info panel lock button")
assertContains('CreateFrame("CheckButton", "ShirsLazyTrixRaidInfoReadyToggle"', "ready raid toggle")
assertContains('readyLabel:SetText("Show all")', "ready raid toggle label")
assertContains('ShirsLazyTrixDB.showRaidInfoReady', "ready raid toggle state")
assertContains('ShirsLazyTrix.GetRaidInfoDisplayEntries', "ready raid display entries")
assertContains('ShirsLazyTrix.FormatRaidInfoDisplayStatus(entry)', "scheduled raid rows show readiness plus reset")
assertContains('if row.raidReady or row.raidScheduled then', "ready scheduled rows use the Ready color")
assertContains('name == "ShirsLazyTrixShowRaidInfoPanel" and ShirsLazyTrixDB.showRaidInfoSchedule == true', "opening LazyTrix raid panel requests enabled CCP schedules")
assertContains('panel.raidInfoRefreshElapsed = 0', "raid panel owns a bounded refresh timer")
assertContains('panel:SetScript("OnUpdate"', "visible raid panel refreshes after CCP replies")
assertContains('if this.raidInfoRefreshElapsed >= 1 then', "raid panel refresh is limited to once per second")
assertContains('ShirsLazyTrix.GetRaidInfoCharacterStatuses', "other-character raid hover data")
assertContains('ShirsLazyTrix.SaveRaidInfoPanelPosition', "saved raid info panel position")
assertContains('dragNote:SetPoint("TOPRIGHT", panel, "TOPRIGHT", -36, -11)', "raid panel drag note left offset")
assertContains('"RAID RESET INFO"', "raid reset panel heading")
assertContains('CreateFrame("Button", "ShirsLazyTrixCooldownArcanite"', "clickable Arcanite row")
assertContains('CreateFrame("Button", "ShirsLazyTrixCooldownSalt"', "clickable Salt Shaker row")
assertContains('CreateFrame("Button", "ShirsLazyTrixCooldownLock"', "cooldown panel lock button")
assertContains('lock.lockLabel = lock:CreateFontString', "asset-independent lock label")
assertContains('dragNote:SetPoint("TOPRIGHT", panel, "TOPRIGHT", -36, -11)', "cooldown drag note left offset")
assertContains('ShirsLazyTrix.SaveCooldownPanelPosition', "saved cooldown panel position")
assertContains('"MERCHANT"', "merchant section heading")
assertContains('"Sell gray items", "autoSellGray"', "gray-only merchant checkbox")
assertContains('"Repair all gear", "autoRepairAll"', "automatic repair checkbox")
assertContains("Gray-only selling. Vendor actions stay independent.", "merchant boundary note")
assertContains('table.insert(UISpecialFrames, "ShirsLazyTrixSettingsFrame")', "Escape closes settings")
assertAbsent("repeatable", "repeatable controls must be removed")

if count('createCheckbox(') ~= 23 then
  error("UI must define exactly twenty-two checkbox calls plus the helper", 2)
end

print("ui-minimal-family-style: PASS")
print("ui-movable-filled-minimap: PASS")
print("ui-ten-setting-structure: PASS")
print("ui-profession-cooldown-structure: PASS")
